import chromadb
from chromadb.utils import embedding_functions

# Use sentence-transformers (downloads from HuggingFace, more reliable)
sentence_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

client = chromadb.PersistentClient(path="E:/Oishee/Thesis/chroma_db")

try:
    client.delete_collection("clinical_guidelines")
except:
    pass

collection = client.create_collection(
    "clinical_guidelines",
    embedding_function=sentence_ef
)

guidelines = [
    {"id": "sepsis_01", "condition": "sepsis", "hop": "diagnosis", "text": "Sepsis-3 Definition: Sepsis is life-threatening organ dysfunction caused by a dysregulated host response to infection. Organ dysfunction is identified as an acute increase of 2 or more points in the SOFA (Sequential Organ Failure Assessment) score, reflecting an overall mortality risk of approximately 10%."},
    {"id": "sepsis_02", "condition": "sepsis", "hop": "screening", "text": "qSOFA (quick SOFA) Screening Criteria: Used for rapid bedside identification of patients with suspected infection likely to have poor outcomes. Score 1 point each for: respiratory rate 22/min or greater, altered mentation (GCS less than 15), and systolic blood pressure 100 mmHg or less. A qSOFA score of 2 or more suggests higher risk of sepsis."},
    {"id": "sepsis_03", "condition": "sepsis", "hop": "septic_shock", "text": "Septic Shock Criteria: Septic shock is a subset of sepsis with circulatory and cellular metabolic dysfunction associated with higher mortality. Identified clinically by: persisting hypotension requiring vasopressors to maintain mean arterial pressure 65 mmHg or greater AND serum lactate greater than 2 mmol/L despite adequate volume resuscitation."},
    {"id": "sepsis_04", "condition": "sepsis", "hop": "treatment", "text": "Sepsis Initial Management (Hour-1 Bundle): Measure lactate level, obtain blood cultures before antibiotics, administer broad-spectrum antibiotics, begin rapid crystalloid fluid resuscitation 30 mL/kg for hypotension or lactate 4 mmol/L or greater, apply vasopressors if hypotensive during or after fluid resuscitation to maintain MAP 65 mmHg or greater."},
    {"id": "sepsis_05", "condition": "sepsis", "hop": "labs", "text": "Sepsis Laboratory Markers: Key markers include elevated white blood cell count (WBC greater than 12000) or low (less than 4000), elevated lactate (greater than 2 mmol/L indicates tissue hypoperfusion), elevated procalcitonin and C-reactive protein, thrombocytopenia, and elevated creatinine indicating renal involvement."},

    {"id": "pneumonia_01", "condition": "pneumonia", "hop": "diagnosis", "text": "Community-Acquired Pneumonia (CAP) Diagnosis per ATS/IDSA: Diagnosis requires demonstrable infiltrate on chest radiograph or other imaging, together with clinical features such as fever, cough, sputum production, dyspnea, and findings on auscultation like crackles or bronchial breath sounds."},
    {"id": "pneumonia_02", "condition": "pneumonia", "hop": "severity", "text": "CURB-65 Severity Score for Pneumonia: One point each for Confusion, Urea greater than 7 mmol/L (BUN greater than 19 mg/dL), Respiratory rate 30/min or greater, Blood pressure low (systolic less than 90 or diastolic 60 mmHg or less), and age 65 or older. Score 0-1 outpatient, 2 consider admission, 3 or more severe requiring hospitalization and possible ICU."},
    {"id": "pneumonia_03", "condition": "pneumonia", "hop": "icu", "text": "ATS/IDSA Criteria for Severe Pneumonia (ICU admission): Major criteria: septic shock requiring vasopressors, or respiratory failure requiring mechanical ventilation. Minor criteria (3 or more): respiratory rate 30/min or greater, PaO2/FiO2 ratio 250 or less, multilobar infiltrates, confusion, uremia, leukopenia, thrombocytopenia, hypothermia, hypotension requiring aggressive fluids."},
    {"id": "pneumonia_04", "condition": "pneumonia", "hop": "treatment", "text": "ATS/IDSA Pneumonia Empiric Antibiotic Treatment: For outpatients without comorbidities, amoxicillin or doxycycline or a macrolide. For inpatients (non-ICU), a respiratory fluoroquinolone or beta-lactam plus macrolide. For ICU patients, beta-lactam plus either macrolide or fluoroquinolone. Adjust based on local resistance and culture results."},
    {"id": "pneumonia_05", "condition": "pneumonia", "hop": "labs", "text": "Pneumonia Laboratory and Imaging Findings: Chest X-ray showing lobar consolidation, infiltrates, or interstitial pattern. Elevated WBC with left shift, elevated inflammatory markers (CRP, procalcitonin). Blood cultures, sputum gram stain and culture, and pulse oximetry showing hypoxemia in severe cases."},

    {"id": "aki_01", "condition": "aki", "hop": "diagnosis", "text": "KDIGO Acute Kidney Injury (AKI) Definition: AKI is diagnosed by any of the following: increase in serum creatinine by 0.3 mg/dL or more within 48 hours, increase in serum creatinine to 1.5 times baseline or more within the prior 7 days, or urine volume less than 0.5 mL/kg/h for 6 hours."},
    {"id": "aki_02", "condition": "aki", "hop": "staging", "text": "KDIGO AKI Staging: Stage 1 - creatinine 1.5 to 1.9 times baseline or increase 0.3 mg/dL or more, or urine output less than 0.5 mL/kg/h for 6 to 12 hours. Stage 2 - creatinine 2.0 to 2.9 times baseline, or urine output less than 0.5 mL/kg/h for 12 hours or more. Stage 3 - creatinine 3.0 times baseline or more, or 4.0 mg/dL or higher, or initiation of renal replacement therapy, or urine output less than 0.3 mL/kg/h for 24 hours or anuria for 12 hours."},
    {"id": "aki_03", "condition": "aki", "hop": "causes", "text": "AKI Etiology Categories: Prerenal (volume depletion, hypotension, sepsis, heart failure reducing renal perfusion), Intrinsic renal (acute tubular necrosis from ischemia or nephrotoxins, glomerulonephritis, interstitial nephritis), and Postrenal (urinary tract obstruction). Sepsis is a leading cause of AKI in hospitalized patients."},
    {"id": "aki_04", "condition": "aki", "hop": "treatment", "text": "KDIGO AKI Management: Treat underlying cause, optimize volume status and hemodynamics, maintain mean arterial pressure, discontinue nephrotoxic agents (NSAIDs, aminoglycosides, contrast), adjust drug dosing for renal function, monitor electrolytes and acid-base balance. Consider renal replacement therapy for refractory hyperkalemia, acidosis, fluid overload, or uremia."},
    {"id": "aki_05", "condition": "aki", "hop": "labs", "text": "AKI Laboratory Monitoring: Serial serum creatinine and BUN, urine output measurement, electrolytes especially potassium, urinalysis for casts and protein, fractional excretion of sodium (FENa less than 1% suggests prerenal, greater than 2% suggests intrinsic), and assessment of acid-base status for metabolic acidosis."},

    # ============ HEART FAILURE (ACC/AHA/HFSA 2022) ============
    {"id": "hf_01", "condition": "heart_failure", "hop": "diagnosis", "text": "Heart Failure Definition per ACC/AHA/HFSA 2022: Heart failure is a complex clinical syndrome resulting from any structural or functional impairment of ventricular filling or ejection of blood. Diagnosis requires symptoms and signs (dyspnea, fatigue, edema, orthopnea, paroxysmal nocturnal dyspnea, rales, elevated jugular venous pressure) together with objective evidence of cardiac dysfunction on echocardiogram or elevated natriuretic peptides (BNP greater than 35 pg/mL or NT-proBNP greater than 125 pg/mL in ambulatory settings; BNP greater than 100 pg/mL or NT-proBNP greater than 300 pg/mL in acute settings)."},
    {"id": "hf_02", "condition": "heart_failure", "hop": "staging", "text": "Heart Failure Classification by Ejection Fraction and NYHA Class: HFrEF (reduced EF) defined as LVEF 40% or less. HFmrEF (mildly reduced) 41 to 49%. HFpEF (preserved) 50% or greater. NYHA Functional Classification: Class I - no limitation of physical activity; Class II - slight limitation, comfortable at rest; Class III - marked limitation, less than ordinary activity causes symptoms; Class IV - unable to carry out any physical activity without symptoms, symptoms at rest. ACC/AHA Stages A through D describe progression from at-risk to advanced heart failure."},
    {"id": "hf_03", "condition": "heart_failure", "hop": "acute_decompensation", "text": "Acute Decompensated Heart Failure (ADHF) Criteria: Rapid onset or worsening of heart failure symptoms requiring urgent therapy. Features include acute pulmonary edema, worsening dyspnea and orthopnea, weight gain from fluid retention, peripheral or pulmonary congestion, hypoxemia (SpO2 less than 90% on room air), and elevated natriuretic peptides. Warm/wet, cold/wet, warm/dry, and cold/dry hemodynamic profiles guide therapy, with cold/wet indicating cardiogenic shock requiring inotropes or mechanical support."},
    {"id": "hf_04", "condition": "heart_failure", "hop": "treatment", "text": "Guideline-Directed Medical Therapy (GDMT) for HFrEF per ACC/AHA/HFSA: Four foundational drug classes - ARNI (sacubitril/valsartan) or ACE inhibitor/ARB, evidence-based beta-blocker (carvedilol, metoprolol succinate, or bisoprolol), mineralocorticoid receptor antagonist (spironolactone or eplerenone), and SGLT2 inhibitor (dapagliflozin or empagliflozin). Loop diuretics (furosemide, torsemide, bumetanide) for volume overload. Titrate to target doses as tolerated. For acute decompensation: IV loop diuretics, oxygen if hypoxemic, and vasodilators if hypertensive."},
    {"id": "hf_05", "condition": "heart_failure", "hop": "labs", "text": "Heart Failure Laboratory and Imaging Findings: Elevated BNP or NT-proBNP proportional to severity. Echocardiogram showing reduced ejection fraction, chamber dilation, or diastolic dysfunction. Chest X-ray showing cardiomegaly, pulmonary vascular congestion, Kerley B lines, or pleural effusion. EKG may show prior infarction, LV hypertrophy, or conduction abnormalities. Basic metabolic panel to assess renal function and electrolytes (hyponatremia and worsening creatinine indicate poor prognosis). Elevated troponin can occur from myocardial strain."},

    # ============ ATRIAL FIBRILLATION (2023 ACC/AHA/ACCP/HRS) ============
    {"id": "afib_01", "condition": "atrial_fib", "hop": "diagnosis", "text": "Atrial Fibrillation Diagnosis per 2023 ACC/AHA/ACCP/HRS: AFib is a supraventricular tachyarrhythmia characterized by uncoordinated atrial activation with consequently ineffective atrial contraction. ECG diagnosis requires absence of distinct P waves, irregularly irregular R-R intervals when AV conduction is not impaired, and atrial cycle length (when visible) usually variable and less than 200 ms (greater than 300 bpm). Documentation of at least 30 seconds on ECG or rhythm strip is required. Clinical presentations range from asymptomatic to palpitations, dyspnea, fatigue, or hemodynamic instability."},
    {"id": "afib_02", "condition": "atrial_fib", "hop": "stroke_risk", "text": "CHA2DS2-VASc Score for Stroke Risk in AFib: One point each for Congestive heart failure, Hypertension, Age 65 to 74, Diabetes mellitus, Vascular disease (prior MI, PAD, or aortic plaque), and female Sex category. Two points each for Age 75 or greater and prior Stroke/TIA/thromboembolism. Score 0 in men or 1 in women - no anticoagulation. Score 1 in men - consider anticoagulation. Score 2 or greater in men or 3 or greater in women - oral anticoagulation recommended."},
    {"id": "afib_03", "condition": "atrial_fib", "hop": "classification", "text": "AFib Classification: Paroxysmal - terminates spontaneously or with intervention within 7 days. Persistent - continuous for more than 7 days. Long-standing persistent - continuous for more than 12 months. Permanent - patient and clinician accept rhythm and rate control alone. Additional categories include valvular AFib (moderate-to-severe mitral stenosis or mechanical valve) which mandates warfarin, and non-valvular AFib. Rapid ventricular response is defined as ventricular rate greater than 110 bpm."},
    {"id": "afib_04", "condition": "atrial_fib", "hop": "treatment", "text": "AFib Management per 2023 ACC/AHA/ACCP/HRS: Two rhythm goals - rate control and/or rhythm control. Rate control agents: beta-blockers (metoprolol, atenolol), non-dihydropyridine calcium channel blockers (diltiazem, verapamil), or digoxin, targeting resting heart rate less than 110 bpm (lenient) or less than 80 bpm (strict). Rhythm control options: cardioversion (electrical or pharmacologic with amiodarone, flecainide, propafenone), antiarrhythmic drugs, or catheter ablation. Anticoagulation with DOACs (apixaban, rivaroxaban, dabigatran, edoxaban) preferred over warfarin for most non-valvular AFib. Warfarin required for valvular AFib with INR target 2 to 3."},
    {"id": "afib_05", "condition": "atrial_fib", "hop": "labs", "text": "AFib Diagnostic Workup: 12-lead ECG confirms the arrhythmia showing absent P waves and irregular ventricular response. Transthoracic echocardiogram to assess left atrial size, ventricular function, and valvular disease. Transesophageal echocardiogram to exclude left atrial appendage thrombus before cardioversion if AFib duration is more than 48 hours or unknown. Thyroid function tests (TSH) to exclude hyperthyroidism as a cause. Electrolytes, renal function (for anticoagulant dosing), and complete blood count. Ambulatory monitoring (Holter or event monitor) for paroxysmal AFib detection."},

    # ============ CORONARY ARTERY DISEASE / MI (ACC/AHA) ============
    {"id": "cad_01", "condition": "cad_mi", "hop": "diagnosis", "text": "Acute Coronary Syndrome (ACS) Diagnosis per ACC/AHA: ACS encompasses ST-elevation myocardial infarction (STEMI), non-ST-elevation myocardial infarction (NSTEMI), and unstable angina. Fourth Universal Definition of MI requires detection of a rise and/or fall of cardiac troponin (preferably high-sensitivity) with at least one value above the 99th percentile upper reference limit, together with at least one of: ischemic symptoms (chest pain or pressure, dyspnea, diaphoresis), new ischemic ECG changes, development of pathologic Q waves, imaging evidence of new loss of viable myocardium or new regional wall motion abnormality, or identification of coronary thrombus on angiography."},
    {"id": "cad_02", "condition": "cad_mi", "hop": "risk_stratification", "text": "ACS Risk Stratification: STEMI defined by new ST elevation at the J point in two contiguous leads (2 mm or greater in V2-V3 for men, 1.5 mm in women; 1 mm elsewhere) or new left bundle branch block with ischemic symptoms. NSTEMI has troponin elevation without ST elevation. Unstable angina has ischemic symptoms without troponin elevation. TIMI risk score (7 variables) and GRACE score stratify short-term mortality risk in NSTE-ACS. Higher scores indicate higher risk and benefit from early invasive strategy."},
    {"id": "cad_03", "condition": "cad_mi", "hop": "chronic_cad", "text": "Chronic Coronary Disease (CCD) per 2023 ACC/AHA: Stable coronary disease includes patients with prior MI, prior revascularization (PCI or CABG), stable angina, or ischemia on stress testing without acute presentation. Diagnostic evaluation includes resting ECG, coronary CT angiography or stress testing (exercise or pharmacologic with imaging), and coronary angiography for high-risk features. Angina classified by Canadian Cardiovascular Society (CCS) Class I to IV based on activity threshold triggering symptoms."},
    {"id": "cad_04", "condition": "cad_mi", "hop": "treatment", "text": "ACS Initial Management per ACC/AHA: For STEMI - primary PCI within 90 minutes of first medical contact preferred, or fibrinolytic therapy within 30 minutes if PCI unavailable within 120 minutes. For NSTE-ACS - early invasive strategy (angiography within 24 hours) for high-risk features. Dual antiplatelet therapy (aspirin 162 to 325 mg loading then 81 mg daily, plus P2Y12 inhibitor - clopidogrel, ticagrelor, or prasugrel). Anticoagulation with heparin, enoxaparin, or bivalirudin. High-intensity statin (atorvastatin 80 mg or rosuvastatin 40 mg). Beta-blocker within 24 hours if no contraindications. ACE inhibitor or ARB, especially with LV dysfunction. Nitroglycerin for ongoing chest pain."},
    {"id": "cad_05", "condition": "cad_mi", "hop": "labs", "text": "CAD/MI Laboratory and Imaging Findings: High-sensitivity cardiac troponin (I or T) is the preferred biomarker - serial measurement at 0 and 1 to 3 hours to detect rise and fall pattern. Elevated CK-MB as secondary marker. 12-lead ECG performed within 10 minutes of presentation, with serial ECGs if initial is nondiagnostic. Echocardiogram to assess regional wall motion abnormalities and left ventricular function. Coronary angiography defines coronary anatomy and identifies culprit lesion. Lipid panel, glycated hemoglobin, renal function, and complete blood count as part of comprehensive workup."},
]

collection.add(
    documents=[g["text"] for g in guidelines],
    metadatas=[{"condition": g["condition"], "hop": g["hop"]} for g in guidelines],
    ids=[g["id"] for g in guidelines]
)

print(f"Knowledge base built! {len(guidelines)} guideline chunks loaded.")
print("Stored in: E:/Oishee/Thesis/chroma_db")