"""
multihop_reasoner.py
The 3-hop clinical reasoning loop. Each hop is generated by the LLM,
then verified by the constraint checker against guidelines.
"""


class MultiHopReasoner:
    def __init__(self, llm, knowledge_base, constraint_checker):
        self.llm = llm
        self.kb = knowledge_base
        self.checker = constraint_checker

        # The 3 hops, each with a focused question
        self.hops = [
            {
                "name": "Hop 1: Identification",
                "instruction": "Based on the patient's symptoms and presentation, "
                               "what is the most likely primary condition? "
                               "State your reasoning in 2-3 sentences."
            },
            {
                "name": "Hop 2: Diagnostic Confirmation",
                "instruction": "Based on the labs, vitals, and clinical findings, "
                               "what diagnostic criteria support or confirm this condition? "
                               "Reference specific values in 2-3 sentences."
            },
            {
                "name": "Hop 3: Management",
                "instruction": "Based on the confirmed condition, what is the recommended "
                               "initial management or treatment approach? Be specific in 2-3 sentences."
            },
        ]

    def _guess_condition(self, text):
        """Simple keyword-based condition hint for guideline filtering."""
        text_low = text.lower()
        if "sepsis" in text_low or "septic" in text_low:
            return "sepsis"
        if "pneumonia" in text_low or "consolidation" in text_low:
            return "pneumonia"
        if "kidney" in text_low or "creatinine" in text_low or "renal" in text_low or "aki" in text_low:
            return "aki"
        return None

    def reason(self, case_text):
        """Run the full 3-hop reasoning chain with verification."""
        trace = []
        accumulated = f"PATIENT CASE:\n{case_text[:2000]}\n\n"  # truncate long notes

        for hop in self.hops:
            # 1. Generate the hop reasoning
            prompt = accumulated + f"\n{hop['instruction']}"
            system_prompt = ("You are a clinical reasoning assistant working step by step. "
                             "Be precise and base your reasoning on the case details.")
            hop_output = self.llm.ask(prompt, system_prompt=system_prompt)

            # 2. Verify this hop against guidelines
            condition_hint = self._guess_condition(hop_output)
            check = self.checker.check_hop(hop_output, condition=condition_hint)

            # 3. Record the trace
            trace.append({
                "hop_name": hop["name"],
                "reasoning": hop_output,
                "verdict": check["verdict"],
                "verification_reason": check["reason"],
                "guidelines_used": check["guidelines_used"],
            })

            # 4. Feed this hop into the next hop's context
            accumulated += f"\n{hop['name']} conclusion: {hop_output}\n"

        return trace


# Quick test when run directly
if __name__ == "__main__":
    import sys
    sys.path.append("E:/Oishee/Thesis/system_c")
    from llm_connector import LLMConnector
    from knowledge_base import KnowledgeBase
    from constraint_checker import ConstraintChecker

    llm = LLMConnector()
    kb = KnowledgeBase()
    checker = ConstraintChecker(llm, kb)
    reasoner = MultiHopReasoner(llm, kb, checker)

    # A clear synthetic sepsis case for testing
    test_case = (
        "A 68-year-old patient presents with fever of 39.2C, respiratory rate 26/min, "
        "heart rate 112, blood pressure 88/54, and confusion. Labs show WBC 18000, "
        "lactate 3.8 mmol/L, and creatinine rising from 1.0 to 1.9 mg/dL. "
        "There is a suspected urinary tract infection."
    )

    print("Running 3-hop reasoning on test case...\n")
    trace = reasoner.reason(test_case)

    for step in trace:
        print("=" * 65)
        print(step["hop_name"])
        print("-" * 65)
        print(f"REASONING: {step['reasoning']}\n")
        print(f"VERIFICATION: [{step['verdict']}]")
        print(f"  {step['verification_reason']}")
        print(f"  Guidelines: {step['guidelines_used']}")
    print("=" * 65)