"""
multihop_reasoner.py
The 3-hop clinical reasoning loop. Each hop is generated by the LLM,
then verified by the constraint checker against guidelines.
"""


class MultiHopReasoner:
    def __init__(self, llm, knowledge_base, constraint_checker):
        self.llm = llm
        self.kb = knowledge_base
        self.checker = constraint_checker

        # The 3 hops, each with a focused question
        self.hops = [
            {
                "name": "Hop 1: Identification",
                "instruction": "Based on the patient's symptoms and presentation, "
                               "what is the most likely primary condition? "
                               "State your reasoning in 2-3 sentences."
            },
            {
                "name": "Hop 2: Diagnostic Confirmation",
                "instruction": "Based on the labs, vitals, and clinical findings, "
                               "what diagnostic criteria support or confirm this condition? "
                               "Reference specific values in 2-3 sentences."
            },
            {
                "name": "Hop 3: Management",
                "instruction": "Based on the confirmed condition, what is the recommended "
                               "initial management or treatment approach? Be specific in 2-3 sentences."
            },
        ]

    def _guess_condition(self, description, transcription):
        """Deterministic keyword-based condition hint for guideline filtering.

        Scores each condition by WEIGHTED keyword hits, weighting the case
        DESCRIPTION (chief complaint / current primary problem) more heavily than
        the full TRANSCRIPTION, whose past-medical-history and incidental labs
        otherwise dilute the current problem. Ties are broken by the priority
        order of keyword_sets below (heart_failure, atrial_fib, cad_mi, sepsis,
        pneumonia, aki). Returns None if no keyword matches anywhere (score 0),
        so out-of-scope cases retrieve unfiltered. If description is empty/missing
        its term contributes 0 and scoring falls back to transcription only.

        NOTE: An LLM-based classifier (temperature=0) was tested for this step
        and REJECTED: on the MoE model (GPT-OSS-120B via OpenRouter) it returned
        different labels for the same input across runs even at temperature=0,
        breaking reproducibility. This deterministic keyword detector is used
        instead; its main known limitation is physiologically coupled conditions
        (esp. sepsis<->AKI), which is reported and analyzed rather than hidden.
        """
        desc_low = (description or "").lower()
        trans_low = (transcription or "").lower()

        # Ordered by tie-break priority: earlier entries win an equal score.
        keyword_sets = {
            "heart_failure": ["heart failure", "chf", "congestive heart", "cardiomyopathy",
                              "ejection fraction", "bnp", "orthopnea", "diuretic", "lasix",
                              "carvedilol"],
            "atrial_fib": ["atrial fibrillation", "afib", "a-fib", "atrial flutter",
                           "cardioversion", "warfarin", "coumadin", "anticoagulation",
                           "diltiazem"],
            "cad_mi": ["myocardial infarction", "coronary artery disease", "acute coronary",
                       "angina", "troponin", "st elevation", "stent", "coronary angiography"],
            "sepsis": ["sepsis", "septic"],
            "pneumonia": ["pneumonia", "consolidation"],
            "aki": ["kidney", "creatinine", "renal", "aki"],
        }

        # DESCRIPTION dominates; TRANSCRIPTION is a low-weight fallback signal.
        W_DESC, W_TRANS = 3, 1
        scores = {
            cond: W_DESC * sum(kw in desc_low for kw in kws)
                  + W_TRANS * sum(kw in trans_low for kw in kws)
            for cond, kws in keyword_sets.items()
        }

        # max() returns the FIRST key with the highest score, and dict iteration
        # preserves insertion order -> ties resolve to the priority order above.
        best = max(scores, key=lambda cond: scores[cond])
        return best if scores[best] > 0 else None

    def reason(self, case_text, condition=None):
        """Run the full 3-hop reasoning chain with verification.

        `condition` is the guideline-filter hint detected upstream (in
        SystemC.analyze_case) from the case description + transcription. When
        None, retrieval runs unfiltered (out-of-scope fallback).
        """
        trace = []
        accumulated = f"PATIENT CASE:\n{case_text[:1200]}\n\n"  # truncate long notes

        for hop in self.hops:
            # 1. Generate the hop reasoning
            prompt = accumulated + f"\n{hop['instruction']}"
            system_prompt = ("You are a clinical reasoning assistant working step by step. "
                             "Be precise and base your reasoning on the case details.")
            hop_output = self.llm.ask(prompt, system_prompt=system_prompt)

            # 2. Verify this hop against guidelines
            check = self.checker.check_hop(hop_output, condition=condition)

            # 3. Record the trace
            trace.append({
                "hop_name": hop["name"],
                "reasoning": hop_output,
                "verdict": check["verdict"],
                "verification_reason": check["reason"],
                "guidelines_used": check["guidelines_used"],
            })

            # 4. Feed this hop into the next hop's context
            accumulated += f"\n{hop['name']} conclusion: {hop_output}\n"

        return trace


# Quick test when run directly
if __name__ == "__main__":
    import sys
    sys.path.append("E:/Oishee/Thesis/system_c")
    from llm_connector import LLMConnector
    from knowledge_base import KnowledgeBase
    from constraint_checker import ConstraintChecker

    llm = LLMConnector()
    kb = KnowledgeBase()
    checker = ConstraintChecker(llm, kb)
    reasoner = MultiHopReasoner(llm, kb, checker)

    # A clear synthetic sepsis case for testing
    test_case = (
        "A 68-year-old patient presents with fever of 39.2C, respiratory rate 26/min, "
        "heart rate 112, blood pressure 88/54, and confusion. Labs show WBC 18000, "
        "lactate 3.8 mmol/L, and creatinine rising from 1.0 to 1.9 mg/dL. "
        "There is a suspected urinary tract infection."
    )

    print("Running 3-hop reasoning on test case...\n")
    trace = reasoner.reason(test_case, condition=reasoner._guess_condition("", test_case))

    for step in trace:
        print("=" * 65)
        print(step["hop_name"])
        print("-" * 65)
        print(f"REASONING: {step['reasoning']}\n")
        print(f"VERIFICATION: [{step['verdict']}]")
        print(f"  {step['verification_reason']}")
        print(f"  Guidelines: {step['guidelines_used']}")
    print("=" * 65)